name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create staging directory
        run: mkdir staging

      - name: Move JAR to staging directory
        run: mv target/*.jar staging

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging/*.jar
          retention-days: 1

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.run_number }}
          title: "Automated Build ${{ github.run_number }}"
          prerelease: false
          files: staging/*.jar
